services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/phub
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
      - redis

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dimitris123@
      MYSQL_DATABASE: phub
      MYSQL_SSL_MODE: 'DISABLED'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www/phub

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  tests:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www/phub
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: Dimitris123@
      DB_PORT: 3306
      DB_NAME: phub
      DB_CHARSET: utf8mb4
      
volumes:
  db_data: