FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    nano \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    cron \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo pdo_mysql \
    && pecl install redis && docker-php-ext-enable redis

WORKDIR /var/www/phub

COPY . /var/www/phub

COPY ./cron/cronfile /etc/cron.d/phub-cron

RUN chmod 0644 /etc/cron.d/phub-cron

RUN crontab /etc/cron.d/phub-cron

RUN touch /var/log/cron.log

CMD ["bash", "-c", "cron && php-fpm"]